version: "3"
services:
  ipo:
    build: .
    restart: on-failure
    container_name: ipo
    networks:
      - ipo-network
    ports:
      - 8081:8081
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql
      - kafka

#  subscribe:
#    build: ../subscribe/
#    restart: on-failure
#    container_name: subscribe
#    networks:
#      - ipo-network
#    ports:
#      - 8082:8082
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    depends_on:
#      - mysql
#      - kafka

  mysql:
    image: mysql
    container_name: mysql
    networks:
      - ipo-network
    environment:
      MYSQL_DATABASE: ipo
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3307:3307

  kafka:
    image: wurstmeister/kafka
    mem_limit: 350m
    container_name: kafka
    networks:
      - ipo-network
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    mem_limit: 350m
    container_name: zookeeper
    networks:
      - ipo-network
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper

networks:
  ipo-network:
    name: ipo-network